
export const SORT_TYPES = {
  PRICE_LOW_TO_HEIGH: 'PRICE_LOW_TO_HEIGH',
  PRICE_HEIGH_TO_LOW: 'PRICE_HEIGH_TO_LOW',
  RATING: 'RATING',
};

export const FILTERS = {
  NAME: 'NAME',
  COLORS: 'COLORS',
  MAX_PRICE: 'MAX_PRICE',
  MIN_PRICE: 'MIN_PRICE',
};