// TODO: Move mock to json-server
const products = [
  {
    id: 1,
    imageUrl: require('./images/Under Armour UA Charged Assert 9-RED 3024590-600.png'),
    name: 'Under Armour UA Charged Assert 9-RED 3024590-600',
    description: 'Men\'s running shoes Under Armour UA Charged Assert 9 are designed to help anyone run faster: Charge Cushioning technology protects against impact, leather overlays provide stability, and the mesh upper keeps your feet cool. Many kilometers ahead.',
    color: 'red',
    price: 2209,
    rating: 4.1,
  },
  {
    id: 2,
    imageUrl: require('./images/CMP Sun Hiking Shoes 31Q4807-02QM.jpg'),
    name: 'CMP Sun Hiking Shoes 31Q4807-02QM',
    description: 'Men\'s CMP sneakers for everyday wear. For trekking. Lace-up. Made of leather. Seasonal. Thick sole. Combined materials. Technologies: Full On Grip, Ortholite.',
    color: 'brown',
    price: 2519,
    rating: 4.4,
  },
  {
    id: 3,
    imageUrl: require('./images/Nike Air Max Dawn DJ3624-001.jpg'),
    name: 'Nike Air Max Dawn DJ3624-001',
    description: 'NIKE AIR MAX SC sneakers - synonymous with freedom and comfort. Thanks to the lightweight lines of the traditional sports look, this item is the perfect addition to any outfit. This model contains at least 20% recycled material and has a breathable and comfortable design for all-day wear.',
    color: 'black',
    price: 6079,
    rating: 4.2,
  },
  {
    id: 4,
    imageUrl: require('./images/Puma Softride Vital Fresh Better 37744004.jpg'),
    name: 'Puma Softride Vital Fresh Better 37744004',
    description: 'Men\'s sneakers Puma Softride Vital Fresh Better combine exceptional comfort and effortless style with a design that will make you feel light on your feet.',
    color: 'red',
    price: 1669,
    rating: 3.9,
  },
  {
    id: 5,
    imageUrl: require('./images/Lacoste Joggeur 742SMA0032-02H.jpg'),
    name: 'Lacoste Joggeur 742SMA0032-02H',
    description: 'Lacoste sneakers - a tribute to the brand\'s sports past combined with modern technology. Their versatility, comfort and practicality will make them favorites in your wardrobe. Suitable for everyday wear.',
    color: 'black',
    price: 6290,
    rating: 3.2,
  },
  {
    id: 6,
    imageUrl: require('./images/New Balance 608 MX608WT.jpg'),
    name: 'New Balance 608 MX608WT',
    description: 'New Balance 608 model is a symbol of the 90s. The voluminous silhouette with a massive sole makes this model one of the most relevant today. This is because fashion is cyclical and bulky footwear is back in trend now.',
    color: 'white',
    price: 2499,
    rating: 2,
  },
  {
    id: 7,
    imageUrl: require('./images/Saucony Jazz 81 70574-2s.jpg'),
    name: 'Saucony Jazz 81 70574-2s',
    description: 'The anniversary model Jazz 81 from Saucony is a traditional style with updated comfort and a familiar legendary design. The versatile footwear is suitable for everyday wear and can be combined well with any wardrobe.',
    color: 'brown',
    price: 2599,
    rating: 1.7,
  },
  {
    id: 8,
    imageUrl: require('./images/Puma Cilia Mode 37112502.jpg'),
    name: 'Puma Cilia Mode 37112502',
    description: 'The design of the cute, playful, feminine Cilia Mode sneakers is inspired by 90s fashion. The SoftFoam + insole ensures unparalleled comfort. You look great and feel great too.',
    color: 'white',
    price: 2690,
    rating: 4.8,
  },
  {
    id: 9,
    imageUrl: require('./images/New Balance 574 U574RA2.jpg'),
    name: 'New Balance 574 U574RA2',
    description: 'Men\'s sneakers from New Balance are made from a combination of suede and synthetic materials. The model is perfect for everyday wear and workouts. It pairs well with any clothing, including jeans and sweatpants.',
    color: 'blue',
    price: 3029,
    rating: 5,
  },
  {
    id: 10,
    imageUrl: require('./images/Stilli SK4871-2.jpg'),
    name: 'Stilli SK4871-2',
    description: 'Footwear is always an important component of a wardrobe. It should be stylish, high-quality, and comfortable. All shoes from Stilli pleasantly surprise with their design and variety, so everyone can find something to their liking.',
    color: 'gray',
    price: 999,
    rating: 4.5,
  },
  {
    id: 11,
    imageUrl: require('./images/Joma C.SAFRON REPELLENT 2224 CSAFRW2224.jpg'),
    name: 'Joma C.SAFRON REPELLENT 2224 CSAFRW2224',
    description: 'Joma is a well-known Spanish brand that produces sports uniforms, footwear, and accessories for team and individual sports.',
    color: 'brown',
    price: 1599,
    rating: 2.7,
  },
  {
    id: 12,
    imageUrl: require('./images/Skechers 220035 BKGY-9.jpg'),
    name: 'Skechers 220035 BKGY-9',
    description: 'Men\'s stylish and comfortable Skechers sneakers. Very lightweight and comfortable model for running. The model provides full comfort during everyday runs and workouts.',
    color: 'black',
    price: 2799,
    rating: 3.6,
  },
  {
    id: 13,
    imageUrl: require('./images/Adidas Originals Ozweego EE6464.jpg'),
    name: 'Adidas Originals Ozweego EE6464',
    description: 'These sneakers represent the style of the late 90s - early 2000s in a new way, combining retro details with futuristic design. The model is made of mesh, suede and smooth synthetic material.',
    color: 'white',
    price: 3999,
    rating: 3.2,
  },
];  

export default products;